---
title: "Consigne travail à la maison"
author: "Paolo Crosetto"
date: "Octobre 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Consigne

1. rendez vous sur https://github.com/rfordatascience/tidytuesday/blob/master/README.md
2. sélectionnez un jeu de données qui vous plaise
3. créez un document Rmarkdown dans votre projet (File -> New -> Rmarkdown...)
4. sur ce document, mélangez du texte et du code 
5. avec le but de
   - décrire les données
   - répondre à au moins 3 questions sur les données
   - chaque réponse doit comprendre du texte, un (ou plus) plots, si vous voulez des régressions ou autres analyses, stat descriptive...
6. Knit-ez le document pour générer un HTML
7. git: commit + push sur votre projet github perso

## Modalité de discussion

1. lors de notre dernière séance vous allez présenter votre HTML
2. en discutant ce que vous avez fait et en utilisant quels outils
3. je peux vous poser des questions
4. et possiblement vous demander de changer / mettre à jour vos analyses sur le moment

## En règle générale

1. pas de stress
2. l'idée est d'apprendre: vous pouvez copier, échanger avec vos camarades, copier-coller du web...
3. ...mais je pourrai vous poser des questions donc ne faites pas plus de ce que vous êtes à l'aise à défendre à l'oral en classe!

## Notes

**Il y aura une note pour ce cours**. Les règles sont les suivantes:

- la note sera basé sur le travail fait et sur la présentation que vous en ferez lors de la dernière séance;
- la note sera en /20;
- vous aurez une note jointe pour le cours 'logiciels spécialisés', qui comprend aussi le cours de python (tenu par Paul Bettega);

## Ressources

1. pour regarder ce que autres ont fait: https://nsgrantham.shinyapps.io/tidytuesdayrocks/
2. Help -> Cheatsheets doit être votre bible et votre ami
3. contactez moi; à tout moment si vous gardez votre repo github à jour je peux voir votre travail et vous aider
