---
title: "Rapport sur la consommation d'énergie en Europe entre 2016 et 2018"
author: "Célia Jourdan"
date: "26/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
tuesdata <- tidytuesdayR::tt_load('2020-08-04')
tuesdata <- tidytuesdayR::tt_load(2020, week = 32)

energy_types <- tuesdata$energy_types
country_totals <- tuesdata$country_totals
```

## Idées de questions:
- Pays qui utilisent le plus d'énergie renouvelable
- Nombre de pays dans des catégories de pourcentage de production d'énergie renouvelables (cat de 20%)
- Correlation entre les importations et l'utilisation d'énergies fossiles

## Questions

#### 1. Pourcentage d'énergie renouvelable par pays en 2018

```{r}
qu1 <- energy_types %>% 
  group_by(country) %>% 
  mutate(total_2018 = sum(`2018`)) %>% 
  filter(type %in% c("Hydro", "Pumped hydro power", "Wind", "Solar", "Geothermal", "Other")) %>% 
  mutate(total_ren_2018 = sum(`2018`)) %>% 
  summarise(pourcent_ren = (total_ren_2018/total_2018)*100, na.rm = F) %>% 
  select(country, pourcent_ren) %>% 
  arrange(-pourcent_ren)

```
















